### ISSUE TITLE
reverting delete when executionOrder is 'remote' → 'local'

### ISSUE THREAD

**Issue by mesqueeb** [vue-sync/core#2]
Currently when executing `delete()` on a doc with execution order: 'remote' → 'local'
the "remote" Store Plugin executes `delete()` first, and there's an error on 'local' deletion, there's no way to revert & therefore re-insert the the data into the 'remote' store.

While this seems unlikely, it can happen when using 2 remote stores.

**Comment by louisameline** [comment]
The remote store should be seen as the source of truth (especially when the order is explicitly remote>local), so it doesn't matter if the local deletion fails afterwards, it should not involve a rollback. It's the local store's issue only, that's on him to deal with it.

It's rather the opposite which is an issue. You delete locally first, then it fails remotely: to rollback, do you load again from remote or do you keep the data somewhere locally until you really know you can give it to the garbage collector? Both can be done, and we might leave it to the user's choice. I'm really interested in how we'll keep a queue of actions that might need a rollback after a remote failure, and how we present it to the user.

Side note: I'm currently interested in knowing if there is something in such a queue waiting to be sinc'ed remotely. Because I want to warn my users who try to log out that they'll lose unsync'ed data if they log out before the synchronization is done.

**Comment by mesqueeb** [comment]
Yeah, rolling back when an action fails is handled by each store-plugin.
I agree with this:
> remote store should be seen as the source of truth (especially when the order is explicitly remote>local), so it doesn't matter if the local deletion fails afterwards, it should not involve a rollback

So it kinda solves my problem 😄
